export const technologies = [
    { name: 'Prometheus', category: 'Devops', logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/2066px-Prometheus_software_logo.svg.png" },
    { name: 'Loki', category: 'Devops', logo: "https://files.readme.io/e5e1b43-grafana-loki.png" },
    { name: 'Bitbucket', category: 'Devops', logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Bitbucket-blue-logomark-only.svg/2048px-Bitbucket-blue-logomark-only.svg.png" },
    { name: 'Gitlab', category: 'Devops', logo: "https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png" },
    { name: 'Kotlin', category: 'Mobile', logo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin_Icon.png" },
    { name: 'Android', category: 'Mobile', logo: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg" },
    { name: 'Java', category: 'Backend', logo: "https://i.postimg.cc/bY6ygV4B/366a3f497b653f18e354f25bd4dd0dce-removebg-preview.png" },
    { name: 'Azure', category: 'Infrastructure', logo: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg" },
    { name: 'GCP', category: 'Infrastructure', logo: "https://static-00.iconduck.com/assets.00/google-cloud-icon-2048x1646-7admxejz.png" },
    { name: 'DigitalOcean', category: 'Infrastructure', logo: "https://upload.wikimedia.org/wikipedia/commons/f/ff/DigitalOcean_logo.svg" },
    { name: 'AWS', category: 'Infrastructure', logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" },
    { name: 'Kubernetes', category: 'Infrastructure', logo: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg" },
    { name: 'ELK', category: 'Devops', logo: "https://companieslogo.com/img/orig/ESTC-4d81ee09.png?t=1720244491" },
    { name: 'Grafana', category: 'Devops', logo: "https://gdm-catalog-fmapi-prod.imgix.net/ProductLogo/1fb6eda1-a890-4065-a959-7af42a3905ec.png" },
    { name: 'Terraform', category: 'Devops', logo: "https://cloudgnosis.org/posts/7-ways-to-implement-iac-on-aws/og-image-8b3e4f7d.png" },
    { name: 'iOS', category: 'Mobile', logo: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Apple_logo_grey.svg" },
    { name: 'Swift', category: 'Mobile', logo: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Swift_logo.svg" },
    { name: 'Flutter', category: 'Mobile', logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/Google-flutter-logo.png" },
    { name: 'Next.JS', category: 'Frontend', logo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg" },
    { name: 'React.JS', category: 'Frontend', logo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" },
    { name: 'Javascript', category: 'Frontend', logo: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png" },
    { name: 'Balsamiq', category: 'UX/UI', logo: "https://images.crunchbase.com/image/upload/c_pad,h_256,w_256,f_auto,q_auto:eco,dpr_1/f8y8dt9knms5f7wsruev" },
    { name: 'Invision', category: 'UX/UI', logo: "https://www.svgrepo.com/show/353911/invision-icon.svg" },
    { name: 'Figma', category: 'UX/UI', logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
    { name: 'Docker', category: 'Devops', logo: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Docker_%28container_engine%29_logo_%28cropped%29.png   " },
    { name: 'PostgreSQL', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg" },
    { name: 'Python', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" },
    { name: 'Node.JS', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg" },
    { name: 'PHP', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg" },
    { name: 'Go', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg" },
    { name: 'Ant Design', category: 'Frontend', logo: "https://static-00.iconduck.com/assets.00/ant-design-icon-512x512-xbdsnx83.png" },
    { name: 'Gatsby.JS', category: 'Frontend', logo: "https://static-00.iconduck.com/assets.00/gatsby-icon-2048x2048-tasa4u9p.png" },
    { name: 'Vue.JS', category: 'Frontend', logo: "https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg" },
    { name: 'Principle', category: 'UX/UI', logo: "https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Principle-512.png" },
    { name: 'Sketch', category: 'UX/UI', logo: "https://cdn.freebiesupply.com/logos/large/2x/sketch-2-logo-png-transparent.png" },
    { name: 'Adobe Suite', category: 'UX/UI', logo: "https://www.pngall.com/wp-content/uploads/13/Adobe-Logo-PNG-Picture.png" },
    { name: 'YouTrack', category: 'Testing', logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/YouTrack_Icon.svg/2048px-YouTrack_Icon.svg.png" },
    { name: 'Appium', category: 'Testing', logo: "https://brandslogos.com/wp-content/uploads/images/large/appium-logo.png" },
    { name: 'Cypress', category: 'Testing', logo: "https://raw.githubusercontent.com/ijsto/cypress-snippets/master/images/logo.png" },
    { name: 'Jmeter', category: 'Testing', logo: "https://jmeter.apache.org/images/jmeter.png" },
    { name: 'MongoDB', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/MongoDB_Logo.svg" },
    { name: 'Cassandra', category: 'Backend', logo: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg" },
    { name: 'Sass', category: 'Frontend', logo: "https://upload.wikimedia.org/wikipedia/commons/9/96/Sass_Logo_Color.svg" },
    { name: 'Material UI', category: 'Frontend', logo: "https://static-00.iconduck.com/assets.00/material-ui-icon-2048x1626-on580ia9.png" },
    { name: 'Zeplin', category: 'UX/UI', logo: "https://seeklogo.com/images/Z/zeplin-logo-5EE095EA20-seeklogo.com.png" },
    { name: 'Illustrator', category: 'UX/UI', logo: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Adobe_Illustrator_CC_icon.svg" },
    { name: 'Lottie', category: 'UX/UI', logo: "https://udevs.io/static/jmeter-52971c702c282adee5c719cb0b0c8a37.svg" },
    { name: 'Photoshop', category: 'UX/UI', logo: "https://upload.wikimedia.org/wikipedia/commons/a/af/Adobe_Photoshop_CC_icon.svg" }
  ];
  

export const categories = ['Frontend', 'Backend', 'Devops', 'Testing', 'UX/UI', 'Infrastructure', 'Mobile'];

