/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      "upload.wikimedia.org",
      "about.gitlab.com",
      "files.readme.io",
      "i.postimg.cc",
      "static-00.iconduck.com",
      "companieslogo.com",
      "gdm-catalog-fmapi-prod.imgix.net",
      "cloudgnosis.org",
      "images.crunchbase.com","cdn2.iconfinder.com","cdn.freebiesupply.com","www.pngall.com","brandslogos.com","raw.githubusercontent.com","seeklogo.com","",
      "digitalocean.com",
      "www.oracle.com",
      "microsoft.com",
      "google.com",
      "aws.com",
      "www.elastic.co",
      "www.terraform.io",
      "apple.com",
      "google.com",
      "docker.com",
      "postgresql.org",
      "python.org",
      "nodejs.org",
      "php.net",
      "golang.org",
      "ant.design",
      "gatsbyjs.org",
      "vuejs.org",
      "principleformac.com",
      "sketch.com",
      "adobe.com",
      "www.jetbrains.com",
      "appium.io",
      "www.cypress.io",
      "jmeter.apache.org",
      "mongodb.com",
      "cassandra.apache.org",
      "sass-lang.com",
      "mui.com",
      "zeplin.io",
      "airbnb.design",
    ],
  },
};

export default nextConfig;
